# Generated by Django 6.0.3 on 2026-03-13 18:37

import django.db.models.deletion
import submissions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('phase', models.CharField(choices=[('phase1', 'Phase 1 — Project Proposal'), ('phase2', 'Phase 2 — Mid-term Review'), ('phase3', 'Phase 3 — Final Submission')], default='phase1', max_length=6)),
                ('file', models.FileField(upload_to=submissions.models.submission_upload_path, validators=[submissions.models.validate_file_extension])),
                ('github_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('reviewed', 'Reviewed')], default='pending', max_length=8)),
                ('teacher_note', models.TextField(blank=True, help_text='Teacher review note')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='teams.team')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
